import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: `${process.env.FOURSQUARE_CLIENT_ID}`
    }
  };
  
  
  const response = await fetch('https://api.foursquare.com/v3/places/nearby?ll=19.082197839427938%2C72.87293569719792&query=Coffee&limit=30', options)
  const data = await response.json()
  console.log("ssss",data.results)

  return {
    props: {
      coffeeStores: data.results,
    },
  };
}

export default function Home(props) {
  // console.log("props:",props)
  const handleOnBannerBtnClick = () => {
    console.log("Hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coffeeIcon.png" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearly"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>

        {props.coffeeStores.length > 0 && (
          <div>
            <h2 className={styles.heading2}>Toronto stores</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl || 'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'}
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
