import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchCoffeeStores } from "../lib/coffee-stores";

import useTrackLocation from "../hooks/use-track-location"


export async function getStaticProps(context) {
  
  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home(props) {
  // console.log("props:",props)
  const {handleTrackLocation, latlong, locationErrorMsg, isFindingLocation} = useTrackLocation();

  console.log({latlong, locationErrorMsg, handleTrackLocation})

  useEffect(async() => {
    if(latlong) {
      try {
        const fetchedCoffeeStores = await fetchCoffeeStores(latlong);
        console.log({fetchedCoffeeStores})
      } catch (error) {
        console.log({error})
      }
    }
  }, [latlong])

  const handleOnBannerBtnClick = () => {
    console.log("Hi banner button");
    handleTrackLocation()
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coffeeIcon.png" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Loading...." : "View stores nearly"}
          handleOnClick={handleOnBannerBtnClick}
        />

        {locationErrorMsg && <h3><b>Something went wrong: {locationErrorMsg}</b></h3>}

        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>

        {props.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto stores</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl || 'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'}
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
